name: Build Cross-Platform Executables

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build Windows executable
        run: |
          pyinstaller app.spec
        # Move output to a dedicated folder for Windows build
      - name: Store Windows executable
        run: mkdir -p build/windows && mv dist/my_app.exe build/windows/

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-executable
          path: build/windows/

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build Linux executable
        run: |
          pyinstaller app.spec
        # Move output to a dedicated folder for Linux build
      - name: Store Linux executable
        run: mkdir -p build/linux && mv dist/my_app build/linux/

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-executable
          path: build/linux/
